name = "worker-trademe-site-stats"
main = "src/index.ts"
compatibility_date = "2022-12-28"
usage_model = "bundled"

[triggers]
crons = [ "* * * * *" ]

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "trademe_api"
database_id = "683d04a1-90ea-41b8-bece-0eabd50bacca"